site_name: Image toolkit
repo_url: https://github.com/reinimax/image-toolkit
theme: 
  name: material
  features:
    - search.suggest
plugins:
  - material/search
  - open-in-new-tab
nav:
    - Home: 'index.md'
    - 'API Reference':
        - 'Processing functions': 'api/operations.md'
# Custom JS for moving pdoc navigation to the sidebar
extra_javascript:
  - custom.js
# Extensions to essentially link to README.md from index.md
markdown_extensions:
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
